// Generated by tools/build.mjs. Version f15e4b20.
const CACHE = 'room-f15e4b20';
const CORE = ['./', 'public/tour/app-9dd98234.js', 'fonts/caveat-latin-81102a.woff2', 'fonts/inter-latin-bec94a.woff2'];
self.addEventListener('install', (e) => { e.waitUntil(caches.open(CACHE).then((c) => c.addAll(CORE)).then(() => self.skipWaiting())); });
self.addEventListener('activate', (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', (e) => {
  const r = e.request, url = new URL(r.url);
  if (r.method !== 'GET' || r.headers.has('range')) return;
  // never-changing files: named by hash, fonts, or pinned to a commit on jsDelivr
  const cdn = url.hostname === 'cdn.jsdelivr.net';
  if (!cdn && url.origin !== location.origin) return;
  if (cdn || /\/public\/tour\/[^/]+-[0-9a-f]{8}\.|\/fonts\//.test(url.pathname)) {
    e.respondWith(caches.open(CACHE).then((c) => c.match(r).then((hit) => hit || fetch(r).then((res) => { if (res.ok) c.put(r, res.clone()); return res; }))));
    return;
  }
  e.respondWith(fetch(r).then((res) => { if (res.ok) caches.open(CACHE).then((c) => c.put(r, res.clone())); return res; }).catch(() => caches.match(r)));
});
