// Stage 3: build the site the visitor gets (index.html, one script, a service worker).
//   node tools/build.mjs            (after tools/encode.mjs)
//
// - src/tour/*.js bundled and minified into public/tour/app-<hash>.js (ES2019, so
//   older Safari runs it too)
// - the CSS (with the self-hosted fonts) and the tour's data (the manifest and the
//   screens' measurements) inlined into index.html: no extra round trips
// - the first view's pictures preloaded; a social preview image (og.jpg)
// - sw.js: a service worker that keeps every hashed file forever, so a second
//   visit loads from disk
import { build } from 'esbuild';
import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import sharp from 'sharp';

const hash = (b) => createHash('sha1').update(b).digest('hex').slice(0, 8);
const OUT = 'public/tour';
const manifest = JSON.parse(readFileSync(`${OUT}/manifest.json`, 'utf8'));
const anchors = JSON.parse(readFileSync('public/anchors.json', 'utf8'));

// 1. the script
const js = await build({ entryPoints: ['src/tour/main.js'], bundle: true, minify: true, format: 'esm', target: ['es2019', 'safari13'],
  write: false, legalComments: 'none' });
const code = js.outputFiles[0].contents;
for (const f of readdirSync(OUT)) if (/^app-[0-9a-f]{8}\.js$/.test(f)) rmSync(`${OUT}/${f}`);
const app = `${OUT}/app-${hash(code)}.js`;
writeFileSync(app, code);

// 1b. the live room (engine/src + three.js), for capable computers
const live = await build({ entryPoints: ['engine/src/main.js'], bundle: true, minify: true, format: 'esm', target: ['es2020'],
  supported: { 'top-level-await': true }, write: false, legalComments: 'none',
  alias: { three: './vendor/three/three.module.js', 'three/addons': './vendor/three/addons' } });
const liveCode = live.outputFiles[0].contents;
for (const f of readdirSync(OUT)) if (/^live-[0-9a-f]{8}\.js$/.test(f)) rmSync(`${OUT}/${f}`);
const liveFile = `${OUT}/live-${hash(liveCode)}.js`;
writeFileSync(liveFile, liveCode);

// 2. the CSS, inlined
const css = await build({ stdin: { contents: readFileSync('fonts/fonts.css', 'utf8') + readFileSync('src/tour/style.css', 'utf8'), loader: 'css' },
  minify: true, write: false, target: ['safari13'] });

// 3. the data, inlined (numbers rounded: millimetres are plenty)
const round = (k, v) => (typeof v === 'number' ? Math.round(v * 1e5) / 1e5 : v);
const data = JSON.stringify({ manifest: { views: manifest.views, moves: manifest.moves }, anchors: { screens: anchors.screens, glass: anchors.glass, door: anchors.door } }, round)
  .replace(/</g, '\\u003c');

// 4. a social preview (link cards in LinkedIn, Slack, iMessage): the room, 1200x630
const room = manifest.views.room.files.front[2048].webp;
const og = await sharp(`${OUT}/${room}`).resize(1200, 1200).extract({ left: 0, top: 285, width: 1200, height: 630 }).jpeg({ quality: 82 }).toBuffer();
for (const f of readdirSync(OUT)) if (/^og-[0-9a-f]{8}\.jpg$/.test(f)) rmSync(`${OUT}/${f}`);
const ogFile = `${OUT}/og-${hash(og)}.jpg`;
writeFileSync(ogFile, og);

// 5. the page
const hall = manifest.views.hall.files;
const caveat = readdirSync('fonts').find((f) => f.startsWith('caveat'));
const html = readFileSync('src/tour/index.html', 'utf8')
  .replaceAll('{{app}}', app)
  .replaceAll('{{live}}', liveFile)
  .replace('{{css}}', css.outputFiles[0].text.trim())
  .replace('{{data}}', data)
  .replace('{{og}}', `https://mazenddr.github.io/${ogFile}`)
  .replace('{{hallStrip}}', `${OUT}/${hall.strip.avif}`)
  .replaceAll('{{hallFront}}', `${OUT}/${hall.front[1024].avif}`)
  .replaceAll('{{hallFrontWebp}}', `${OUT}/${hall.front[1024].webp}`)
  .replace('{{caveat}}', caveat);
writeFileSync('index.html', html);

// 6. the service worker: hashed files are immutable (cache first); the page and
//    the apps are fetched fresh when online and served from the cache when not.
const version = hash(html);
writeFileSync('sw.js', `// Generated by tools/build.mjs. Version ${version}.
const CACHE = 'room-${version}';
const CORE = ['./', '${app}', 'fonts/${caveat}', 'fonts/${readdirSync('fonts').find((f) => f.startsWith('inter'))}'];
self.addEventListener('install', (e) => { e.waitUntil(caches.open(CACHE).then((c) => c.addAll(CORE)).then(() => self.skipWaiting())); });
self.addEventListener('activate', (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener('fetch', (e) => {
  const r = e.request, url = new URL(r.url);
  if (r.method !== 'GET' || url.origin !== location.origin || r.headers.has('range')) return;
  if (/\\/public\\/tour\\/[^/]+-[0-9a-f]{8}\\.|\\/fonts\\//.test(url.pathname)) {
    e.respondWith(caches.open(CACHE).then((c) => c.match(r).then((hit) => hit || fetch(r).then((res) => { if (res.ok) c.put(r, res.clone()); return res; }))));
    return;
  }
  e.respondWith(fetch(r).then((res) => { if (res.ok) caches.open(CACHE).then((c) => c.put(r, res.clone())); return res; }).catch(() => caches.match(r)));
});
`);
const gz = (b) => Math.round(b.length / 1024);
console.log(`index.html ${gz(Buffer.from(html))} KB, ${app} ${gz(code)} KB, ${liveFile} ${gz(liveCode)} KB, og ${gz(og)} KB`);
